### ISSUE TITLE
Log files show missing outputs

### ISSUE THREAD

**Issue by KaasBallard** [ianvcaldas/smalldisco#1]
Hello, I am attempting to use your smalldisco Snakemake pipeline to identify putative siRNAs and I noticed that the log files indicate there was some kind of error during the process. The error appears to have affected all of the jobs within the pipeline, as all the jobs in the log file have something similar to this in the reason section:
`reason: Missing output files: .smalldisco/sirna/exon-list-with-overlaps.bed`

The shell command I used for this run is:
`python smalldisco.py sirna -a path/to/my/gtf.gtf path/to/my/BAM/folder/`

I have included the log file in question.

Note that I do get a .bed file from the run, I am just concerned about this behavior in the log file. 

[smalldisco.snakemake.log](https://github.com/ianvcaldas/smalldisco/files/13445264/smalldisco.snakemake.log)

**Comment by ianvcaldas** [comment]
The good news is that this is not an error – Snakemake is reporting the reason each step of the pipeline ran. _Because_ the output files aren't there (yet), Snakemake runs that step of the pipeline, which then generates the files.

If you have the final .bed result, everything ran successfully and you are good to go. Thank you for using smalldisco!
