### ISSUE TITLE
 singularity pull?

### ISSUE THREAD

**Issue by LIUXING-bio** [ianvcaldas/smalldisco#3]
Hi, Is there a way to install software using singularity pull?

**Comment by ianvcaldas** [comment]
Hi,

We have not implemented smalldisco in a Singularity container, and at the moment we don't have plans to do so. I'm sorry about that – I will re-open this issue if that changes.

Best wishes,
Ian

**Comment by LIUXING-bio** [comment]
If it can be used, this software will be better used by everyone because currently it seems that installation is prone to problems

---- Replied Message ----
| From | ***@***.***> |
| Date | 04/29/2024 22:55 |
| To | ianvcaldas/smalldisco ***@***.***> |
| Cc | LIUXING-bio ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ianvcaldas/smalldisco] singularity pull? (Issue #3) |

Hi,

We have not implemented smalldisco in a Singularity container, and at the moment we don't have plans to do so. I'm sorry about that – I will re-open this issue if that changes.

Best wishes,
Ian
